name: Go Build

on:
  push:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env: &env-vars
      TITLE: ${{ github.event.head_commit.message || 'No Title' }}

    steps:
    - name: Echo Title
      run: |
        echo "Commit Title: ${{ env.TITLE }}"

    - name: Direct
      run: |
        echo "Commit Title: ${{ github.event.head_commit.message }}"

  echo:
    runs-on: ubuntu-latest
    env: *env-vars
    steps:
    - name: Echo Title
      run: |
        echo "Commit Title: ${{ env.TITLE }}"
